# Generated by Django 2.2.5 on 2019-09-29 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name': 'Contact Details', 'verbose_name_plural': 'Contact Details'},
        ),
    ]
